### ISSUE TITLE
Count parameter not working

### ISSUE THREAD

**Issue by starrv** [wh-iterabb-it/meowfacts#181]
I tried the url to get more than one cat fact but it  is not working ie curl https://meowfacts.herokuapp.com/?count=3.

**Comment by tarzzi** [comment]
This happens due to wrong evaluation of count parameter, on the invalidCountMiddleware function.

``` javascript
    request.query.count != undefined
``` 

Changing evaluation to equals, fixes the issue :

``` javascript
    request.query.count == undefined
```

**Comment by BeauBouchard** [comment]
Deployed and tested solution from @tarzzi  in #182 

https://meowfacts.herokuapp.com/?count=3

 should be working now, Big thanks to @tarzzi for fixing, and @starrv thanks for pointing out the bug! :clap:
