### ISSUE TITLE
Help Translating 3 facts into Ukrainian and Russian facts

### ISSUE THREAD

**Issue by BeauBouchard** [wh-iterabb-it/meowfacts#184]
Big thanks to [amiarham](https://github.com/amiarham) who added 3 facts to [eng-US.js](https://github.com/wh-iterabb-it/meowfacts/blob/main/src/models/localization/eng-US.js#L98) in https://github.com/wh-iterabb-it/meowfacts/pull/183 . 

We now need to translate these 3 facts into the other 2 locals to make sure we are having the same experience for all languages we support. 

```
  "Cats can jump up to six times their length.",
  "Cats have contributed to the extinction of 33 different species.",
  "Cats can drink sea water in order to survive.",
```

## Acceptance Criteria 

* [ ] Translate the above 3 facts to Ukrainian in [ukr-UA.js](https://github.com/wh-iterabb-it/meowfacts/blob/main/src/models/localization/ukr-UA.js)
*  [ ] Translate the above 3 facts to Russian in [rus-RU.js](https://github.com/wh-iterabb-it/meowfacts/blob/main/src/models/localization/rus-RU.js)

**Comment by amiarham** [comment]
Hi there Beau Bouchard I am here to help I will translate it and create a pull request, Thanks

**Comment by BeauBouchard** [comment]
Thanks for the help @amiarham :clap:
