### ISSUE TITLE
sst

### ISSUE THREAD

**Issue by switchhalt** [wh-iterabb-it/meowfacts#195]
### Description of Problem

we can no longer `npm install` correctly without github access credentials for the sst repo (?)(unsure)

## Causes 

recently sst and i think a dep from it made it so it can't be installed. 

This causes development to break noted in https://github.com/wh-iterabb-it/meowfacts/pull/194

## Solution and Mitigation

We need to refactor a few functions out of SST or fix SST https://github.com/wh-iterabb-it/sst which hasn't had its issue identified yet.

**Comment by switchhalt** [comment]
CC @BeauBouchard

**Comment by BeauBouchard** [comment]
fixed in https://github.com/wh-iterabb-it/meowfacts/pull/208
