### ISSUE TITLE
[i18n] Español MX 

### ISSUE THREAD

**Issue by BeauBouchard** [wh-iterabb-it/meowfacts#209]
# Call for Translator Help 

Facts needed Translating in  `Spanish MX` Localization [esp-mx](https://github.com/wh-iterabb-it/meowfacts/blob/main/src/models/localization/esp-MX.js)

Please make any PR that adds additional translated facts to the file. 

Main Issue: https://github.com/wh-iterabb-it/meowfacts/issues/175

**Comment by Whiskydog** [comment]
I'm willing to help! Already forked and created a branch, could I get assigned the issue?

There's also these facts in the file:

```
"Para darse de baja de catfacts, responda el siguiente código: tj3G5de$se",
"¡Tienes que ser gatito me! ¿Estás seguro de que quieres darte de baja? envía SÍ o NO",
```

They roughly translate to "To unsubscribe from catfacts, answer with the following code..." and "You've got to be _kitting_ me! Are you sure you want to unsubscribe? Answer YES or NO."

They seem to reference some sort of SMS subscription, which is weird... I'd be willing to remove them in my contribution but maybe they're there on purpose?

**Comment by BeauBouchard** [comment]
Thank you for considering working on this issue! Feel free to add or revise that to something you believe fits better. Localizations are best when they fit the specific location's culture and language both. There are a lot of "American" cat facts, which i would love to be more global or specific for the location and language. 

Rare Repository Lore and SMS Context: originally catfacts was an elaborate prank SMS service, where your friends could get these as text messages once a day. a harmless and funny practical joke's dataset decade later, it has become more of a wholesome actual repository of cat facts that helps open source creator learn and make first contributions to open source.

**Comment by BeauBouchard** [comment]
thank you for all your efforts @Whiskydog
