### ISSUE TITLE
Returning Undefined

### ISSUE THREAD

**Issue by Soarezin** [wh-iterabb-it/meowfacts#214]
Hey guys, I'm trying to make an app in React Native that returns the cats facts, with axios, but it keeps returning undefined, can somebody help me with this?

![image](https://user-images.githubusercontent.com/94654478/201248632-ddfb47b3-d8e0-4fd6-b04a-8ee08efa47a2.png)

![image](https://user-images.githubusercontent.com/94654478/201248666-058c6809-2faa-4511-9f62-204ab3bd7e9b.png)

**Comment by BeauBouchard** [comment]
Weird, did you get an answer to this? 
I am actually going to try to make a tutorial so we can have a working example for you in a little bit. https://github.com/wh-iterabb-it/meowfacts/issues/218


Mind uploading your example in a repo? I would love to help contribute/fix it if there was an issue.

**Comment by Soarezin** [comment]
Hey, i manage to work this out like this

const PuxaFato = useCallback(() => {
    axios
.get('https://meowfacts.herokuapp.com/')
.then(res => {
      setData(res.data.data);
      setLoading(false);
    });
