### ISSUE TITLE
/options endpoint

### ISSUE THREAD

**Issue by BeauBouchard** [wh-iterabb-it/meowfacts#219]
**Description of changes**

Creating a new endpoint at `/options` which returns an array of language objects in its response. 
Each local/language in the `./localization` folder should get its own object.

`lang` object displaying the following attributes: 

* locale_code - legacy locale codes which were ISO 2 digit
* iso_code -  the 3 digit ISO 639-2/T Code
* full_code - both `iso_code` and `locale_code` separated by a dash `-`, example: "ces-cz"
* english_name - English name of Language
* local_name - local name of Language
* full_name - The full name consists of `local_name`, `english_name` and `full_code`, like `Čeština/Czech (ces-cz)`
* fact_count - the number of facts translated into this language

example of response: 
```json
{
  "lang": [
    {
      "locale_code": "cz",
      "iso_code": "ces",
      "full_code": "ces-cz",
      "local_name": "Čeština", 
      "english_name": "Czech",
      "full_name": "Čeština/Czech (ces-cz)",
      "fact_count": 94,
    },
    {
      "locale_code": "de",
      "iso_code": "deu",
      "full_code": "deu-de",
      "local_name": "Deutsch",
      "english_name": "German",
      "full_name": "Deutsch/German (deu-de)",
      "fact_count": 99,
    }
  ]
}
```

This will allow the discovery of which languages are available, and how many facts are available in each.

**Comment by furkanmutlu** [comment]
Hi @BeauBouchard I would like to work on this.

**Comment by BeauBouchard** [comment]
thank you again @furkanmutlu  :D
