### ISSUE TITLE
[bug] Fix default language for multi-language locales

### ISSUE THREAD

**Issue by BeauBouchard** [wh-iterabb-it/meowfacts#220]
Querying `esp` has 2 files it can go to in `./src/models/localizations` folder, we wanted originally to one to be the default, if the short code is used for the request. 

Example of bug: 

User is querying the endpoint with `?lang=esp` 

We want to control the default behavior to go to the `esp-es` or `esp-mx` response.

**Comment by furkanmutlu** [comment]
Hi @BeauBouchard, can you assign this to me ?
