### ISSUE TITLE
Italian translation

### ISSUE THREAD

**Issue by RobyP77** [wh-iterabb-it/meowfacts#249]
Hi, I would like to contribute with an italian translation. Please let me know how to do that. Thanks

**Comment by BeauBouchard** [comment]
@RobyP77 I made an issue at https://github.com/wh-iterabb-it/meowfacts/issues/255 specifically for Italian translation, It has some instructions on what file to create, and a starter. Please feel free to change some of the facts to be more specific for the local, as a lot of it was focused on the americas when created in english. 
Thank you for considering the contribution and making an issue :D
