### ISSUE TITLE
[i18n] Italian 'ita-it' translation

### ISSUE THREAD

**Issue by BeauBouchard** [wh-iterabb-it/meowfacts#255]
# Call for Translator Help 
### Minimal requirements 
* [ ] Create a new file named `ita-it.js` in the `src/models/localization/` folder
* [ ] use the template below to get started, but translate some other cat facts from the other file into that file
* [ ] make a PR and mention this Issue in the description. 

### Starting Template Example 

```javascript
const facts = [
  "a single fact per a line :D",
  "..."
];

const langName = "Italian",
  langISO = "ita",
  langLocale = "it",
  langLocaleName = "Italy";

module.exports = {
  langName,
  langISO,
  langLocale,
  langLocaleName,
  code: `${langISO}-${langLocale}`,
  codeName: `${langName} (${langLocaleName})`,
  facts: facts,
};
```

Feel free to change the facts to be more meaningful to the location you want, as the original English facts are with America in mind, I would love to see what other places have for accurate and high-quality facts about cats.

English name of Language: `Italian`
ISO 639-2/BT Language Code: `ita` 
Language Dialect Local: `Italy`

Please make any PR that adds additional translated facts to the file. 

> Note: Please forgive me if I use language or terminology incorrectly, please do correct me and we will all learn together how things are expressed differently in other places. 

Main Issue: https://github.com/wh-iterabb-it/meowfacts/issues/175

**Comment by AdwaitKulkarni58** [comment]
@BeauBouchard Can you assign me the issue so I can work on it?

**Comment by AdwaitKulkarni58** [comment]
Made the required changes and created a PR with the branch name feature/italian-translation
