### ISSUE TITLE
Want to add Bengali language

### ISSUE THREAD

**Issue by dshaw0004** [wh-iterabb-it/meowfacts#318]
I know bengali very well so I want to add bengali language support to this api.

Does it have any contribution docs to guide me how to add a new language support ?

Add a contribution guide.

**Comment by BeauBouchard** [comment]
Awesome idea, Thanks for making an issue, I added a new issue with more precise instructions that i can assign to you. 
I am going to close this issue and use that new one here: 
https://github.com/wh-iterabb-it/meowfacts/issues/321
