### ISSUE TITLE
[i18n] Bengali 'ben-in' translation #304 

### ISSUE THREAD

**Issue by BeauBouchard** [wh-iterabb-it/meowfacts#321]
# Call for Translator Help 

Facts needed Translating in Bengali for India location

### Acceptance Criteria

* [x] Create a new file `./src/models/localizations/ben-in.js`
* [x] Using the Template below, translate existing and even add new cat facts in the localized language. 

### Template

```
const facts = [
  "..."
];

const langName = "bengali",
	langISO = "ben",
	langLocale = "in",
	langLocaleName = "India";

module.exports = {
	langName,
	langISO,
	langLocale,
	langLocaleName,
	code: `${langISO}-${langLocale}`,
	codeName: `${langName} (${langLocaleName})`,
	facts: facts,
};
```

Inspired by  https://github.com/wh-iterabb-it/meowfacts/issues/318 from Main Issue: https://github.com/wh-iterabb-it/meowfacts/issues/175

**Comment by dshaw0004** [comment]
> # Call for Translator Help
> Facts needed Translating in Bengali for India location
> 
> ### Acceptance Criteria
> * [x]  Create a new file `./src/models/localizations/ben-in.js`
> * [x]  Using the Template below, translate existing and even add new cat facts in the localized language.
> 
> ### Template
> ```
> const facts = [
>   "..."
> ];
> 
> const langName = "bengali",
> 	langISO = "ben",
> 	langLocale = "in",
> 	langLocaleName = "India";
> 
> module.exports = {
> 	langName,
> 	langISO,
> 	langLocale,
> 	langLocaleName,
> 	code: `${langISO}-${langLocale}`,
> 	codeName: `${langName} (${langLocaleName})`,
> 	facts: facts,
> };
> ```
> 
> Inspired by #318 from Main Issue: #175

I am folowing this template and I will try to translate all of this asap

**Comment by BeauBouchard** [comment]
@dshaw0004 No worries, your work was  great! I merged it into a dev branch just to fix a linting error. I am merging it in now in https://github.com/wh-iterabb-it/meowfacts/pull/322 which completes your works merge into main. 

Once again, thank you so much for your contribution, you have helped make this API available in a whole new language and local and we appreciate it!

**Comment by BeauBouchard** [comment]
:clap:  
https://meowfacts.herokuapp.com/?lang=ben-in shows up for me now after deploy

**Comment by dshaw0004** [comment]
I can also help you to add hindi language but i can not write hindi that efficiently it will took a long time.
