### ISSUE TITLE
Taiwan is NOT country!!!

### ISSUE THREAD

**Issue by liutianle20** [wh-iterabb-it/meowfacts#386]
The table head of language specifications is not correct. Taiwan should be a province instead of a country.

**Comment by liutianle20** [comment]
Maybe make the head of the column Location(Country/Region) and make the region of that row Chinese Taipei. I appreciate your respect.

**Comment by BeauBouchard** [comment]
The column header is `Localization (country)` to inform people about the API's ability to localize things by dialects. 

None of the areas listed are regions denoting geographical features like Taiwan is an island or its in the region of the South China Seas which Taiwan is also in. but I would say Taiwan is not a region by most definitions. 

What is it you are trying to solve? our goal is not to provide people with a list of countries or sovereign providences, only locals that we translate our cat facts into
