### ISSUE TITLE
is count query parameter not working?

### ISSUE THREAD

**Issue by 0thThing** [wh-iterabb-it/meowfacts#98]
https://meowfacts.herokuapp.com/?count=4 only returns a single fact still? perhaps I am using it wrong?

**Comment by Timoteoo** [comment]
Actually, the app itself does not accept any query parameters.

**Comment by BeauBouchard** [comment]
Sorry, i broke it and removed it in a previous refactor. I should bring that feature back. Excuse the difference in the docs to what is being offered. I am going to make an issue to address this (i forgot) :D

**Comment by BeauBouchard** [comment]
Fixed in https://github.com/wh-iterabb-it/meowfacts/pull/151
